@startuml

scale 550 width

初始化: 待创建订单
订单已创建: 已插入订单记录
订单取消中: 订单待取消
订单已取消: 订单失效结束
待支付: 已生成支付单

[*] --> 初始化

初始化 --> 订单已创建 : 创建新订单
订单已创建 --> 订单取消中: 事件:用户取消\n动作:记录取消原因
订单已创建 --> 订单取消中: 事件:商家取消\n动作:记录取消原因
订单取消中 --> 订单已取消: 事件:请求处理取消订单\n动作:解锁(恢复)库存

订单已创建 --> 待支付: 事件:用户发起支付\n动作:生成支付单,\n关联支付单号与订单;



@enduml