system:
  name: Practice
  charset: UTF-8
  env: testcase

server:
  servlet:
    context-path: /
    application-display-name: ${system.name}
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain






spring:
  application:
    name: ${system.name}

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      write-dates-as-timestamps: false
    property-naming-strategy: SNAKE_CASE
#  redis:
#    database: 0
#    ## autotest-server通过hosts文件配置
#    host: autotest-server
#    port: 6379
#    password:
#    timeout: 5000
#    jedis:
#      pool:
#        max-active: 10
#        max-idle: 10
#        max-wait: -1
#        min-idle: 0
  datasource:
    druid:
      stat-view-servlet:
        loginUsername: test
        loginPassword: 123
      username: root
      password: ROOT_123456
      ## autotest-server通过hosts文件配置
      url: ${DB.url:jdbc:mysql://10.30.30.27:3306/smartdoorlock-app?serverTimezone=UTC}
      connection-init-sqls: set names utf8mb4
      ## 连接池配置 ##
      # 初始化时连接池连接数量
      initial-size: 3
      # 最大连接数
      max-active: 20
      # 连接池最小连接数量
      min-idle: 3
      # 取连接前是否测试连接是否有效,通过validation-query方式
      test-on-borrow: false
      validation-query: select version();



mybatis:
  mapper-locations: classpath*:com/isc/mapper/*.xml


mybatis-plus:
  mapper-locations: classpath*:com/isc/mapper/*.xml

