system:
  name: Practice
  charset: UTF-8
  env: testcase

server:
  servlet:
    context-path: /
    application-display-name: ${system.name}
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain






spring:
  application:
    name: ${system.name}

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      write-dates-as-timestamps: false
    property-naming-strategy: SNAKE_CASE


