/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_isc_NativeMethod */

#ifndef _Included_com_isc_NativeMethod
#define _Included_com_isc_NativeMethod
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_isc_NativeMethod
 * Method:    say
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_isc_NativeMethod_say
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_isc_NativeMethod
 * Method:    getSomeContent
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_isc_NativeMethod_getSomeContent
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
